<?php
/**
 * @file
 * Code for the HPS Search feature.
 */

include_once 'hps_search.features.inc';

/**
 * Implements hook_entity_info_alter().
 */
function hps_search_entity_info_alter(&$entity_info) {
  $entity_info['node']['view modes']['hps_search_results'] = array(
    'label' => 'Search Results',
    'custom settings' => FALSE
  );
}

/**
 * Implements hook_form_views_exposed_form_alter().
 */
function hps_search_form_views_exposed_form_alter(&$form, &$form_state, $form_id) {
  if ($form['#id'] == 'views-exposed-form-hps-search-page-search') {
    $form['text']['#attributes'] = array('placeholder' => t('Search...'));
  }
}
