<?php

/**
 * @file dspaced.install
 * Installation file for DSpaced module.
 */

/**
 * Implements hook_install().
 */
function dspaced_install() {
  // @note Nothing to do here, by default we rely on dspaced_entities module for
  //   creating the required bundles and fields.
}

/**
 * Implements hook_uninstall().
 */
function dspaced_uninstall() {
  // Delete any settings variables
  variable_del('dspaced_repository_rest_baseurl');
  variable_del('dspaced_community_dspace_entity_ids');
}
